baseURL: "https://miguelsalemos.com"
languageCode: "en-us"
title: "Miguel Sá Lemos"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
disqusShortname: miguelsalemos
#googleAnalytics: G-DWJJVE27WD

markup:
  goldmark:
    renderer:
      unsafe: true

# Menus:
#   main:
#     - identifier: blog
#       name: Blog
#       title: Blog posts
#       url: /blogs
#       weight: 1

#     - identifier: gallery
#       name: Gallery
#       title: Blog posts
#       url: /gallery
#       weight: 2

    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Miguel Sá Lemos"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    disableThemeToggle: true
    defaultTheme: "dark"

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    brandLogo: "/fav.png" # Logo for the brand | default is the favicon variable
    brandName: "Miguel" # Brand name for the brand | default is the title variable
    disableSearch: true

  menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Miguel."
    subtitle: "Jack of all (IT) trades."
    content: "A passionate IT Engineer. I assess resources, implement systems and troubleshoot issues."
    image: "photo4.png"
    button:
      enable: true
      name: "Resume"
      url: "#"
      download: true
      newPage: true
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/ta-oma
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/miguel-s%C3%A1-lemos/
      # customIcons:
      #   - icon: 
      #     url: "https://example.com"

  # About
  about:
    enable: true
    title: "About Me"
    image: "photo5.jpg"
    content: |-
      I am a systems engineer with a passion for system administration and cloud computing. I have a technical background in computer science, and have a strong interest for several other areas of IT. I am currently working as a systems Engineer at [Urban Sports Group](https://urbansportsclub.com/en/) in Berlin, Germany. 
      I'm a big fan of travelling, learning new languages and I have lately took on 3D modelling.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Google Workspace"
        - "Okta"
        - "Kandji & JAMF Pro"
        - "Azure & Intune"
        - "Python"
        - "HTML/CSS/JS"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "IT Systems Engineer"
        company: "Urban Sports Group"
        companyUrl: "https://urbansportsclub.com/en/"
        companyLogo: "usg-white.png"
        date: "Aug 2022 - present"
        featuredLink:
          enable: true
          name: "More about the company"
          url: "https://example.com"
        content: "I am currently working as a systems Engineer at [Urban Sports Group](https://urbansportsclub.com/en/) in Berlin, Germany. I am currently working on implementing MDM for the whole company and restructuring their network infrastructure. I'm also responsible for many other SaaS/PaaS and build documentation on those products."

      - job: "IT Technician"
        company: "Miniclip"
        companyUrl: "https://miniclip.com/"
        companyLogo: "miniclip.png"
        date: "Oct 2020 - Aug 2022"
        featuredLink:
          enable: true
          url: "https://miniclip.com/"
        info:
          enable: true
          content: I worked as a IT Technician at Miniclip for nearly 2 years.
        content: |
          I worked as a IT Technician at [Miniclip](https://www.miniclip.com/) in Oeiras, Portugal. I worked on and supported several projects, including:
          - Supported the design of the network, AV and security infrastructure for a newly-built, ~500 PAX capacity office.
          - Implemented Sharepoint as the go-to tool for team collaboration, and trained several team leads on the tool. 
      - job: "B2B Technician"
        company: "Abreu B2B"
        companyUrl: "https://abreuonline.com/Default.aspx"
        companyLogo: "abreu.png"
        date: "Jan 2020 - Aug 2020"
        info:
          enable: false
        featuredLink:
          enable: true
          url: "https://abreuonline.com/Default.aspx"
        content: |
          In a multinational travel organization like Abreu, with thousands of B2B clients, my main responsabilities were:
          - Conduct performance tests per client in order to ensure the correct use of the system (Booking API);
          - Monitor metrics in order to guarantee a good system performance and stable connection;
          - Prepare reports to support the commercial areas in order to identify business opportunities for Abreu Online;
          - Certify, test and monitor new purchase connections in order to ensure system stability depending on clients' traffic through the API.

  # Education
  education:
    enable: true
    # title: "Custom Name"
    # index: true
    items:
      - title: "BSc Computer Science"
        school:
          name: "ISCTE-IUL, Lisbon"
          url: "https://www.iscte-iul.pt/"
        date: "2014"
        #GPA: "3.8 out of 5.0"
        content: |-
          Completed 120/180 ECTS towards a BSc in Computer Science.
      - title: "Sonicwall Training Course"
        school:
          name: "WelcomeWeb - Official Sonicwall Partner"
          url: "https://www.welcomeweb.it/"
        date: "2020"
        #GPA: "3.9 out of 5.0"
        content: |-
          I took the official Sonicwall Training Course on configuring, maintaining and security Sonicwall firewall and router appliances, as part of an ongoing networking training provided by the company.
        featuredLink:
          enable: false
          name: "My academic record"
          url: "https://example.com"
      - title: "High School"
        school:
          name: "EPL - CPEA"
          url: "http://www.eplubango.pt/"
        GPA: "17 out of 20"
        featuredLink:
          enable: false
          url: "https://example.com"

  # Achievements
  achievements:
    enable: false
    # title: "Custom Name"
    items:
      - title: Google kickstart runner
        content: I solved all problems with optimal solution.
        url: https://example.com
      - title: Facebook Hackathon Winner
        content: Developed a product using Artificial Intelligence.
      - title: Hugo Profile
        content: Developed a theme and getting 1K+ downloads per month.
        url: "https://github.com/gurusabarish/hugo-profile"
      - title: Microsoft Imagine Runner
        content: We are developed a product which can help others.
      - title: Google Summer of Code
        content: Contributed to a open source project.
        url: https://example.com

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: Advent of Code
        content: Advent of Code is an annual set of Christmas-themed computer programming challenges that follow an Advent calendar. I'm hoping to participate every year and have my own solution code on Github.
        image: "aoc.png"
        featured:
          name: Challenges
          link: https://adventofcode.com/
          badges:
            - "Python"
        #   - "Bootstrap"
        links:
          - icon: fab fa-github
            url: https://github.com/ta-oma/advent_of_code


  #Contact
  contact:
    enable: true
    title: "Talk to me!"
    content: My inbox is always open. Whether you have something you want to discuss or just want to say hi, I’ll try my best to get back to you!
    email: miguelssalemos@gmail.com
    btnName: Email me

  footer:
    # recentPosts: false
    socialNetworks:
      github: https://github.com/ta-oma
      linkedin: https://www.linkedin.com/in/miguel-s%C3%A1-lemos/